#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[repr(u32)]
pub enum SyntaxKind {
    LowerIdent,
    UpperIdent,
    Number,
    StringLit,
    DefKw,
    LetKw,
    InKw,
    EvalKw,
    RecordKw,
    ExternKw,
    InductiveKw,
    ClassKw,
    InstanceKw,
    AliasKw,
    StructKw,
    TheoremKw,
    MatchKw,
    Equal,
    Assign,
    EqualEqual,
    BangEqual,
    FatArrow,
    Arrow,
    Product,
    Colon,
    DoubleColon,
    Comma,
    Dot,
    Semicolon,
    Pipe,
    At,
    Underscore,
    Lambda,
    LParen,
    RParen,
    LBrace,
    RBrace,
    LBracket,
    RBracket,
    Plus,
    Minus,
    Star,
    Slash,
    Less,
    Greater,
    LessEqual,
    GreaterEqual,
    Whitespace,
    Comment,
    Error,
    SourceFile,
    DefDecl,
    EvalDecl,
    RecordDecl,
    ExternDecl,
    InductiveDecl,
    ClassDecl,
    InstanceDecl,
    AliasDecl,
    AttributeList,
    Attribute,
    ExplicitBinder,
    ImplicitBinder,
    InstanceBinder,
    DefBody,
    PatternMatchArms,
    PatternMatchArm,
    VarPat,
    CtorPat,
    WildcardPat,
    TuplePat,
    LitPat,
    VarExpr,
    CtorExpr,
    AppExpr,
    LambdaExpr,
    LetExpr,
    LitExpr,
    TupleExpr,
    ProjExpr,
    HoleExpr,
    UnitExpr,
    ArrowExpr,
    ArrayExpr,
    PiExpr,
    SigmaExpr,
    InfixExpr,
    RecordLitExpr,
    MatchExpr,
    QualifiedName,
    RecordField,
    RecordFieldList,
    InstanceMember,
    InstanceMemberList,
    InductiveCtor,
    InductiveCtorList,
}

impl SyntaxKind {
    #[must_use]
    pub fn is_trivia(self) -> bool {
        matches!(self, SyntaxKind::Whitespace | SyntaxKind::Comment)
    }
}

impl cstree::Syntax for SyntaxKind {
    fn from_raw(raw: cstree::RawSyntaxKind) -> Self {
        assert!(raw.0 < 128, "bad SyntaxKind raw value: {}", raw.0);
        unsafe { core::mem::transmute(raw.0) }
    }

    fn into_raw(self) -> cstree::RawSyntaxKind {
        cstree::RawSyntaxKind(self as u32)
    }

    fn static_text(self) -> Option<&'static str> {
        match self {
            SyntaxKind::DefKw => Some("def"),
            SyntaxKind::LetKw => Some("let"),
            SyntaxKind::InKw => Some("in"),
            SyntaxKind::EvalKw => Some("eval"),
            SyntaxKind::RecordKw => Some("record"),
            SyntaxKind::ExternKw => Some("extern"),
            SyntaxKind::InductiveKw => Some("inductive"),
            SyntaxKind::ClassKw => Some("class"),
            SyntaxKind::InstanceKw => Some("instance"),
            SyntaxKind::AliasKw => Some("alias"),
            SyntaxKind::StructKw => Some("struct"),
            SyntaxKind::TheoremKw => Some("theorem"),
            SyntaxKind::Equal => Some("="),
            SyntaxKind::Assign => Some(":="),
            SyntaxKind::EqualEqual => Some("=="),
            SyntaxKind::BangEqual => Some("!="),
            SyntaxKind::FatArrow => Some("=>"),
            SyntaxKind::Colon => Some(":"),
            SyntaxKind::DoubleColon => Some("::"),
            SyntaxKind::Comma => Some(","),
            SyntaxKind::Dot => Some("."),
            SyntaxKind::Semicolon => Some(";"),
            SyntaxKind::Pipe => Some("|"),
            SyntaxKind::At => Some("@"),
            SyntaxKind::Underscore => Some("_"),
            SyntaxKind::LParen => Some("("),
            SyntaxKind::RParen => Some(")"),
            SyntaxKind::LBrace => Some("{"),
            SyntaxKind::RBrace => Some("}"),
            SyntaxKind::LBracket => Some("["),
            SyntaxKind::RBracket => Some("]"),
            SyntaxKind::Plus => Some("+"),
            SyntaxKind::Minus => Some("-"),
            SyntaxKind::Star => Some("*"),
            SyntaxKind::Slash => Some("/"),
            SyntaxKind::Less => Some("<"),
            SyntaxKind::Greater => Some(">"),
            SyntaxKind::LessEqual => Some("<="),
            SyntaxKind::GreaterEqual => Some(">="),
            _ => None,
        }
    }
}
