use crate::module::name::{IntrinsicName, QualifiedName};

pub const PRIM_NAT: QualifiedName = QualifiedName::Intrinsic(IntrinsicName::Nat);
pub const PRIM_FIN: QualifiedName = QualifiedName::Intrinsic(IntrinsicName::Fin);
pub const PRIM_STRING: QualifiedName = QualifiedName::Intrinsic(IntrinsicName::Str);
pub const PRIM_ARRAY: QualifiedName = QualifiedName::Intrinsic(IntrinsicName::Array);
pub const PRIM_ARRAY_NIL: QualifiedName = QualifiedName::Intrinsic(IntrinsicName::ArrayNil);
pub const PRIM_ARRAY_CONS: QualifiedName = QualifiedName::Intrinsic(IntrinsicName::ArrayCons);
pub const PRIM_IO: QualifiedName = QualifiedName::Intrinsic(IntrinsicName::IO);
pub const PRIM_HADD: QualifiedName = QualifiedName::Intrinsic(IntrinsicName::HAdd);
pub const PRIM_ADD: QualifiedName = QualifiedName::Intrinsic(IntrinsicName::Add);
pub const PRIM_HSUB: QualifiedName = QualifiedName::Intrinsic(IntrinsicName::HSub);
pub const PRIM_SUB: QualifiedName = QualifiedName::Intrinsic(IntrinsicName::Sub);
pub const PRIM_HMUL: QualifiedName = QualifiedName::Intrinsic(IntrinsicName::HMul);
pub const PRIM_MUL: QualifiedName = QualifiedName::Intrinsic(IntrinsicName::Mul);
pub const PRIM_HDIV: QualifiedName = QualifiedName::Intrinsic(IntrinsicName::HDiv);
pub const PRIM_DIV: QualifiedName = QualifiedName::Intrinsic(IntrinsicName::Div);
pub const PRIM_BEQ: QualifiedName = QualifiedName::Intrinsic(IntrinsicName::BEq);
pub const PRIM_EQ: QualifiedName = QualifiedName::Intrinsic(IntrinsicName::Eq);
pub const PRIM_BNEQ: QualifiedName = QualifiedName::Intrinsic(IntrinsicName::BNeq);
pub const PRIM_NEQ: QualifiedName = QualifiedName::Intrinsic(IntrinsicName::Neq);
pub const PRIM_HLT: QualifiedName = QualifiedName::Intrinsic(IntrinsicName::HLt);
pub const PRIM_LT: QualifiedName = QualifiedName::Intrinsic(IntrinsicName::Lt);
pub const PRIM_HLEQ: QualifiedName = QualifiedName::Intrinsic(IntrinsicName::HLeq);
pub const PRIM_LEQ: QualifiedName = QualifiedName::Intrinsic(IntrinsicName::Leq);
pub const PRIM_HGEQ: QualifiedName = QualifiedName::Intrinsic(IntrinsicName::HGeq);
pub const PRIM_GEQ: QualifiedName = QualifiedName::Intrinsic(IntrinsicName::Geq);
pub const PRIM_HGT: QualifiedName = QualifiedName::Intrinsic(IntrinsicName::HGt);
